### ISSUE TITLE
Fail to run draw_scenes_no_vis

### ISSUE THREAD

**Issue by wowlegchout** [yizhuoyang/AV-PedAware#1]
![image](https://github.com/yizhuoyang/AV-PedAware/assets/126863688/52a1c661-0622-4a35-ad83-98d9a21f88b2)
I use this function like this ⬆
But raise error:
![image](https://github.com/yizhuoyang/AV-PedAware/assets/126863688/0255429c-2790-41fd-bff3-514666675f1f)

**Comment by yizhuoyang** [comment]
![Screenshot from 2024-04-25 16-45-18](https://github.com/yizhuoyang/AV-PedAware/assets/50855744/0f68d273-313e-4ac9-8d3b-410d7229fe93)
try to add these codes in the beginning of the function of draw_scenes_no_vis() to see whether is works

**Comment by wowlegchout** [comment]
Thanks! I tried and no error reported. However, I find saved image pure black, without any point cloud, is it ok? Can a 3D image be saved in jpg format?

**Comment by yizhuoyang** [comment]
![Screenshot from 2024-04-25 17-02-50](https://github.com/yizhuoyang/AV-PedAware/assets/50855744/5dc2f6fd-0a48-47fa-b923-eaa60317f507)
The reason may be that the setting is specifically designed for av-ped dataset, delete or comment the ctr related codes and try

**Comment by wowlegchout** [comment]
Thanks! I tried comment these codes, but saved image still pure black

**Comment by snakehaihai** [comment]
U need to give more details for him to troubleshoot

> Thanks! I tried comment these codes, but saved image still pure black
